// <auto-generated />
namespace TimeTracker.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db01));
        
        string IMigrationMetadata.Id
        {
            get { return "201803091718296_db01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
