//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int ProfileId { get; set; }
        public int TabId { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> Add { get; set; }
        public Nullable<int> Edit { get; set; }
        public Nullable<int> Delete { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Tab Tab { get; set; }
    }
}
