//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrier()
        {
            this.CarrierLanguages = new HashSet<CarrierLanguage>();
            this.CarrierTaxRulesGroupShops = new HashSet<CarrierTaxRulesGroupShop>();
            this.Groups = new HashSet<Group>();
            this.Shops = new HashSet<Shop>();
            this.Zones = new HashSet<Zone>();
            this.CartRules = new HashSet<CartRule>();
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> TaxRulesGroupId { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> ShippingHandling { get; set; }
        public Nullable<int> RangeBehavior { get; set; }
        public Nullable<int> IsModule { get; set; }
        public Nullable<int> IsFree { get; set; }
        public Nullable<int> ShippingExternal { get; set; }
        public Nullable<int> NeedRange { get; set; }
        public string ExternalModuleName { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> MaxWidth { get; set; }
        public Nullable<int> MaxHeight { get; set; }
        public Nullable<int> MaxDepth { get; set; }
        public Nullable<double> MaxWeight { get; set; }
        public Nullable<int> grade { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrierLanguage> CarrierLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrierTaxRulesGroupShop> CarrierTaxRulesGroupShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zone> Zones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartRule> CartRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
