//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            this.CartRules = new HashSet<CartRule>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public string DeliveryOption { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> AddressDeliveryId { get; set; }
        public Nullable<int> AddressInvoiceId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public string SecureKey { get; set; }
        public Nullable<int> recyclable { get; set; }
        public Nullable<int> gift { get; set; }
        public string GiftMessage { get; set; }
        public Nullable<int> MobileTheme { get; set; }
        public Nullable<int> AllowSeperatedPackage { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartRule> CartRules { get; set; }
    }
}
