//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartRule()
        {
            this.CartRuleLangs = new HashSet<CartRuleLang>();
            this.Carts = new HashSet<Cart>();
            this.Carriers = new HashSet<Carrier>();
            this.Countries = new HashSet<Country>();
            this.Groups = new HashSet<Group>();
            this.Shops = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> QuantityPerUser { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> PartialUse { get; set; }
        public string code { get; set; }
        public Nullable<double> MinimumAmount { get; set; }
        public Nullable<int> MinimumAmountTax { get; set; }
        public Nullable<int> MinimumAmountCurrency { get; set; }
        public Nullable<int> MinimumAmountShipping { get; set; }
        public Nullable<int> CountryRestriction { get; set; }
        public Nullable<int> CarrierRestriction { get; set; }
        public Nullable<int> GroupRestriction { get; set; }
        public Nullable<int> CartRuleRestriction { get; set; }
        public Nullable<int> ProductRestriction { get; set; }
        public Nullable<int> ShopRestriction { get; set; }
        public Nullable<int> FreeShipping { get; set; }
        public Nullable<double> ReductionPercent { get; set; }
        public Nullable<double> ReductionAmount { get; set; }
        public Nullable<int> ReductionTax { get; set; }
        public Nullable<int> ReductionCurrency { get; set; }
        public Nullable<int> ReductionProduct { get; set; }
        public Nullable<int> GiftProduct { get; set; }
        public Nullable<int> GiftProductAttribute { get; set; }
        public Nullable<int> highlight { get; set; }
        public Nullable<int> active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CartRuleCombination CartRuleCombination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartRuleLang> CartRuleLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrier> Carriers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
