//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionAdvice
    {
        public int ConditionId { get; set; }
        public int AdviceId { get; set; }
        public Nullable<int> display { get; set; }
    
        public virtual Advice Advice { get; set; }
        public virtual Condition Condition { get; set; }
    }
}
