//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationKpiLanguage
    {
        public int ConfigurationKpiId { get; set; }
        public int LanguageId { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
    
        public virtual ConfigurationKpi ConfigurationKpi { get; set; }
        public virtual Language Language { get; set; }
    }
}
