//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationKpi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigurationKpi()
        {
            this.ConfigurationKpiLanguages = new HashSet<ConfigurationKpiLanguage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Shop_Id { get; set; }
        public Nullable<int> ShopGroup_GroupId { get; set; }
        public Nullable<int> ShopGroup_ShopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurationKpiLanguage> ConfigurationKpiLanguages { get; set; }
        public virtual ShopGroup ShopGroup { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
