//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Connection()
        {
            this.ConnectionsPages = new HashSet<ConnectionsPage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<long> IpAddress { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string HttpReferer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectionsPage> ConnectionsPages { get; set; }
    }
}
