//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronjob
    {
        public int Id { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string description { get; set; }
        public string task { get; set; }
        public Nullable<int> hour { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> OneShot { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
