//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerThread
    {
        public int Id { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string status { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
    }
}
