//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizationField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomizationField()
        {
            this.CustomizationFieldLangs = new HashSet<CustomizationFieldLang>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> required { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomizationFieldLang> CustomizationFieldLangs { get; set; }
    }
}
