//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizationFieldLang
    {
        public int CustomizationFieldId { get; set; }
        public int LanguageId { get; set; }
        public int ShopId { get; set; }
        public string name { get; set; }
    
        public virtual CustomizationField CustomizationField { get; set; }
        public virtual Language Language { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
