//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMessage
    {
        public int Id { get; set; }
        public Nullable<int> CustomerThreadId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string message { get; set; }
        public string FileName { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
        public Nullable<int> @private { get; set; }
        public Nullable<int> read { get; set; }
    }
}
