//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.MessageReadeds = new HashSet<MessageReaded>();
            this.TabModulePreferences = new HashSet<TabModulePreference>();
            this.Shops = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastPasswdGen { get; set; }
        public Nullable<System.DateTime> StatsDateFrom { get; set; }
        public Nullable<System.DateTime> StatsDateTo { get; set; }
        public Nullable<System.DateTime> StatsCompareFrom { get; set; }
        public Nullable<System.DateTime> StatsCompareTo { get; set; }
        public Nullable<int> StatsCompareOption { get; set; }
        public string PreselectDateRange { get; set; }
        public string BoColor { get; set; }
        public string BoTheme { get; set; }
        public string BoCss { get; set; }
        public Nullable<int> DefaultTab { get; set; }
        public Nullable<int> BoWidth { get; set; }
        public Nullable<int> BoMenu { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> optin { get; set; }
        public Nullable<int> LastOrderId { get; set; }
        public Nullable<int> LastCustomerMessageId { get; set; }
        public Nullable<int> LastCustomerId { get; set; }
        public Nullable<System.DateTime> LastConnectionDate { get; set; }
        public Nullable<int> Language_Id { get; set; }
    
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageReaded> MessageReadeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabModulePreference> TabModulePreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
