//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeatureValue()
        {
            this.FeatureValueLangs = new HashSet<FeatureValueLang>();
            this.LayeredIndexableFeatureValueLangValues = new HashSet<LayeredIndexableFeatureValueLangValue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public Nullable<int> custom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureValueLang> FeatureValueLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayeredIndexableFeatureValueLangValue> LayeredIndexableFeatureValueLangValues { get; set; }
    }
}
