//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int Id { get; set; }
        public Nullable<int> OperatingSystemId { get; set; }
        public Nullable<int> WebBrowserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> javascript { get; set; }
        public Nullable<int> ScreenResolutionX { get; set; }
        public Nullable<int> ScreenResolutionY { get; set; }
        public Nullable<int> ScreenColor { get; set; }
        public Nullable<int> SunJava { get; set; }
        public Nullable<int> AdobeFlash { get; set; }
        public Nullable<int> AdobeDirector { get; set; }
        public Nullable<int> AppleQuicktime { get; set; }
        public Nullable<int> RealPlayer { get; set; }
        public Nullable<int> WindowsMedia { get; set; }
        public string AcceptLanguage { get; set; }
        public Nullable<int> MobileTheme { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
