//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomesliderSlidesLang
    {
        public int HomesliderSlidesId { get; set; }
        public int LanguageId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string legend { get; set; }
        public string url { get; set; }
        public string image { get; set; }
    
        public virtual HomesliderSlide HomesliderSlide { get; set; }
        public virtual Language Language { get; set; }
    }
}
