//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class HookModule
    {
        public int ModuleId { get; set; }
        public int HookId { get; set; }
        public int ShopId { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual Hook Hook { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SystemModule SystemModule { get; set; }
    }
}
