//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoLang
    {
        public int InfoId { get; set; }
        public int LanguageId { get; set; }
        public string text { get; set; }
    
        public virtual Info Info { get; set; }
        public virtual Language Language { get; set; }
    }
}
