//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language()
        {
            this.AdviceLangs = new HashSet<AdviceLang>();
            this.AttachmentLangs = new HashSet<AttachmentLang>();
            this.AttributeGroupLangs = new HashSet<AttributeGroupLang>();
            this.AttributeLangs = new HashSet<AttributeLang>();
            this.BadgeLangs = new HashSet<BadgeLang>();
            this.CarrierLanguages = new HashSet<CarrierLanguage>();
            this.CartRuleLangs = new HashSet<CartRuleLang>();
            this.CategoryLanguages = new HashSet<CategoryLanguage>();
            this.CmsBlockLangs = new HashSet<CmsBlockLang>();
            this.CmsCategoryLanguages = new HashSet<CmsCategoryLanguage>();
            this.CmsLangs = new HashSet<CmsLang>();
            this.ConfigurationKpiLanguages = new HashSet<ConfigurationKpiLanguage>();
            this.ConfigurationLanguages = new HashSet<ConfigurationLanguage>();
            this.ContactLanguages = new HashSet<ContactLanguage>();
            this.CountryLanguages = new HashSet<CountryLanguage>();
            this.CustomizationFieldLangs = new HashSet<CustomizationFieldLang>();
            this.Employees = new HashSet<Employee>();
            this.FeatureLangs = new HashSet<FeatureLang>();
            this.FeatureValueLangs = new HashSet<FeatureValueLang>();
            this.GenderLangs = new HashSet<GenderLang>();
            this.GroupLanguages = new HashSet<GroupLanguage>();
            this.HomesliderSlidesLangs = new HashSet<HomesliderSlidesLang>();
            this.ImageLangs = new HashSet<ImageLang>();
            this.InfoLangs = new HashSet<InfoLang>();
            this.LayeredIndexableAttributeGroupLangValues = new HashSet<LayeredIndexableAttributeGroupLangValue>();
            this.LayeredIndexableAttributeLangValues = new HashSet<LayeredIndexableAttributeLangValue>();
            this.LayeredIndexableFeatureLangValues = new HashSet<LayeredIndexableFeatureLangValue>();
            this.LayeredIndexableFeatureValueLangValues = new HashSet<LayeredIndexableFeatureValueLangValue>();
            this.ManufacturerLangs = new HashSet<ManufacturerLang>();
            this.MetaLangs = new HashSet<MetaLang>();
            this.OrderMessageLangs = new HashSet<OrderMessageLang>();
            this.OrderReturnStateLangs = new HashSet<OrderReturnStateLang>();
            this.OrderStateLangs = new HashSet<OrderStateLang>();
            this.ProductCommentCriterionLangs = new HashSet<ProductCommentCriterionLang>();
            this.ProductLangs = new HashSet<ProductLang>();
            this.ProfileLanguages = new HashSet<ProfileLanguage>();
            this.QuickAccessLangs = new HashSet<QuickAccessLang>();
            this.RiskLangs = new HashSet<RiskLang>();
            this.SceneLangs = new HashSet<SceneLang>();
            this.ShopLanguages = new HashSet<ShopLanguage>();
            this.StockMvtReasonLangs = new HashSet<StockMvtReasonLang>();
            this.SupplierLangs = new HashSet<SupplierLang>();
            this.SupplyOrderStateLangs = new HashSet<SupplyOrderStateLang>();
            this.TabLanguages = new HashSet<TabLanguage>();
            this.TaxLangs = new HashSet<TaxLang>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string IsoCode { get; set; }
        public string LanguageCode { get; set; }
        public string DateFormatLite { get; set; }
        public string DateFormatFull { get; set; }
        public Nullable<int> IsRtl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviceLang> AdviceLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentLang> AttachmentLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeGroupLang> AttributeGroupLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeLang> AttributeLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadgeLang> BadgeLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrierLanguage> CarrierLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartRuleLang> CartRuleLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryLanguage> CategoryLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmsBlockLang> CmsBlockLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmsCategoryLanguage> CmsCategoryLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmsLang> CmsLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurationKpiLanguage> ConfigurationKpiLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurationLanguage> ConfigurationLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactLanguage> ContactLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryLanguage> CountryLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomizationFieldLang> CustomizationFieldLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureLang> FeatureLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureValueLang> FeatureValueLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenderLang> GenderLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupLanguage> GroupLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomesliderSlidesLang> HomesliderSlidesLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageLang> ImageLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoLang> InfoLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayeredIndexableAttributeGroupLangValue> LayeredIndexableAttributeGroupLangValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayeredIndexableAttributeLangValue> LayeredIndexableAttributeLangValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayeredIndexableFeatureLangValue> LayeredIndexableFeatureLangValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayeredIndexableFeatureValueLangValue> LayeredIndexableFeatureValueLangValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturerLang> ManufacturerLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaLang> MetaLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMessageLang> OrderMessageLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderReturnStateLang> OrderReturnStateLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStateLang> OrderStateLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCommentCriterionLang> ProductCommentCriterionLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLang> ProductLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileLanguage> ProfileLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuickAccessLang> QuickAccessLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskLang> RiskLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceneLang> SceneLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopLanguage> ShopLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMvtReasonLang> StockMvtReasonLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierLang> SupplierLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyOrderStateLang> SupplyOrderStateLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabLanguage> TabLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxLang> TaxLangs { get; set; }
    }
}
