//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayeredCategory
    {
        public int Id { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ValueId { get; set; }
        public string type { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> FilterType { get; set; }
        public Nullable<int> FilterShowLimit { get; set; }
    }
}
