//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayeredPriceIndex
    {
        public int ProductId { get; set; }
        public int CurrencyId { get; set; }
        public int ShopId { get; set; }
        public Nullable<int> PriceMin { get; set; }
        public Nullable<int> PriceMax { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
