//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayeredIndexableFeature
    {
        public int FeatureId { get; set; }
        public Nullable<int> indexable { get; set; }
    
        public virtual Feature Feature { get; set; }
    }
}
