//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemcachedServer
    {
        public int Id { get; set; }
        public string ip { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<int> weight { get; set; }
    }
}
