//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaLang
    {
        public int MetaId { get; set; }
        public int ShopId { get; set; }
        public int LanguageId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string keywords { get; set; }
        public string UrlRewrite { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Meta Meta { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
