//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePreference
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string module { get; set; }
        public Nullable<int> interest { get; set; }
        public Nullable<int> favorite { get; set; }
    }
}
