//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleAccess
    {
        public int ProfileId { get; set; }
        public int ModuleId { get; set; }
        public Nullable<int> view { get; set; }
        public Nullable<int> configure { get; set; }
        public Nullable<int> uninstall { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual SystemModule SystemModule { get; set; }
    }
}
