//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReturnDetail
    {
        public int OrderReturnId { get; set; }
        public int OrderDetailId { get; set; }
        public int CustomizationId { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual OrderReturn OrderReturn { get; set; }
    }
}
