//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderInvoice()
        {
            this.OrderInvoicePayments = new HashSet<OrderInvoicePayment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> DeliveryNumber { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> TotalDiscountTaxExcl { get; set; }
        public Nullable<double> TotalDiscountTaxIncl { get; set; }
        public Nullable<double> TotalPataxExclId { get; set; }
        public Nullable<double> TotalPataxInclId { get; set; }
        public Nullable<double> TotalProducts { get; set; }
        public Nullable<double> TotalProductsWt { get; set; }
        public Nullable<double> TotalShippingTaxExcl { get; set; }
        public Nullable<double> TotalShippingTaxIncl { get; set; }
        public Nullable<int> ShippingTaxComputationMethod { get; set; }
        public Nullable<double> TotalWrappingTaxExcl { get; set; }
        public Nullable<double> TotalWrappingTaxIncl { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInvoicePayment> OrderInvoicePayments { get; set; }
    }
}
