//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCarrier
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> OrderInvoiceId { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> ShippingCostTaxExcl { get; set; }
        public Nullable<double> ShippingCostTaxIncl { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    }
}
