//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSlipDetail
    {
        public int OrderSlipId { get; set; }
        public int OrderDetailId { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<double> UnitPriceTaxExcl { get; set; }
        public Nullable<double> UnitPriceTaxIncl { get; set; }
        public Nullable<double> TotalPriceTaxExcl { get; set; }
        public Nullable<double> TotalPriceTaxIncl { get; set; }
        public Nullable<double> AmountTaxExcl { get; set; }
        public Nullable<double> AmountTaxIncl { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual OrderSlip OrderSlip { get; set; }
    }
}
