//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSlip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderSlip()
        {
            this.OrderSlipDetails = new HashSet<OrderSlipDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<double> ConversionRate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<double> TotalProductsTaxExcl { get; set; }
        public Nullable<double> TotalProductsTaxIncl { get; set; }
        public Nullable<double> TotalShippingTaxExcl { get; set; }
        public Nullable<double> TotalShippingTaxIncl { get; set; }
        public Nullable<int> ShippingCost { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> ShippingCostAmount { get; set; }
        public Nullable<int> partial { get; set; }
        public Nullable<int> OrderSlipType { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSlipDetail> OrderSlipDetails { get; set; }
    }
}
