//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string reference { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> AddressDeliveryId { get; set; }
        public Nullable<int> AddressInvoiceId { get; set; }
        public Nullable<int> CurrentState { get; set; }
        public string SecureKey { get; set; }
        public string payment { get; set; }
        public Nullable<double> ConversionRate { get; set; }
        public string module { get; set; }
        public Nullable<int> recyclable { get; set; }
        public Nullable<int> gift { get; set; }
        public string GiftMessage { get; set; }
        public Nullable<int> MobileTheme { get; set; }
        public string ShippingNumber { get; set; }
        public Nullable<double> TotalDiscounts { get; set; }
        public Nullable<double> TotalDiscountsTaxIncl { get; set; }
        public Nullable<double> TotalDiscountsTaxExcl { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public Nullable<double> TotalPataxInclId { get; set; }
        public Nullable<double> TotalPataxExclId { get; set; }
        public Nullable<double> TotalParealId { get; set; }
        public Nullable<double> TotalProducts { get; set; }
        public Nullable<double> TotalProductsWt { get; set; }
        public Nullable<double> TotalShipping { get; set; }
        public Nullable<double> TotalShippingTaxIncl { get; set; }
        public Nullable<double> TotalShippingTaxExcl { get; set; }
        public Nullable<double> CarrierTaxRate { get; set; }
        public Nullable<double> TotalWrapping { get; set; }
        public Nullable<double> TotalWrappingTaxIncl { get; set; }
        public Nullable<double> TotalWrappingTaxExcl { get; set; }
        public Nullable<int> RoundMode { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> DeliveryNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> valid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
