//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderState()
        {
            this.OrderStateLangs = new HashSet<OrderStateLang>();
        }
    
        public int Id { get; set; }
        public Nullable<int> invoice { get; set; }
        public Nullable<int> SendEmail { get; set; }
        public string ModuleName { get; set; }
        public string color { get; set; }
        public Nullable<int> unremovable { get; set; }
        public Nullable<int> hidden { get; set; }
        public Nullable<int> logable { get; set; }
        public Nullable<int> delivery { get; set; }
        public Nullable<int> shipped { get; set; }
        public Nullable<int> paid { get; set; }
        public Nullable<int> PdfInvoice { get; set; }
        public Nullable<int> PdfDelivery { get; set; }
        public Nullable<int> deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStateLang> OrderStateLangs { get; set; }
    }
}
