//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.OrderReturnDetails = new HashSet<OrderReturnDetail>();
            this.OrderSlipDetails = new HashSet<OrderSlipDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderInvoiceId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductAttributeId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
        public Nullable<int> ProductQuantityRefunded { get; set; }
        public Nullable<int> ProductQuantityReturn { get; set; }
        public Nullable<int> ProductQuantityReinjected { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<double> ReductionPercent { get; set; }
        public Nullable<double> ReductionAmount { get; set; }
        public Nullable<double> ReductionAmountTaxIncl { get; set; }
        public Nullable<double> ReductionAmountTaxExcl { get; set; }
        public Nullable<double> GroupReduction { get; set; }
        public Nullable<double> ProductQuantityDiscount { get; set; }
        public string ProductEan13 { get; set; }
        public string ProductUpc { get; set; }
        public string ProductReference { get; set; }
        public string ProductSupplierReference { get; set; }
        public Nullable<double> ProductWeight { get; set; }
        public Nullable<int> TaxRulesGroupId { get; set; }
        public Nullable<int> TaxComputationMethod { get; set; }
        public string TaxName { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> ecotax { get; set; }
        public Nullable<double> EcotaxTaxRate { get; set; }
        public Nullable<int> DiscountQuantityApplied { get; set; }
        public string DownloadHash { get; set; }
        public Nullable<int> DownloadNb { get; set; }
        public Nullable<System.DateTime> DownloadDeadline { get; set; }
        public Nullable<double> TotalPriceTaxIncl { get; set; }
        public Nullable<double> TotalPriceTaxExcl { get; set; }
        public Nullable<double> UnitPriceTaxIncl { get; set; }
        public Nullable<double> UnitPriceTaxExcl { get; set; }
        public Nullable<double> TotalShippingPriceTaxIncl { get; set; }
        public Nullable<double> TotalShippingPriceTaxExcl { get; set; }
        public Nullable<double> PurchaseSupplierPrice { get; set; }
        public Nullable<double> OriginalProductPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderReturnDetail> OrderReturnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSlipDetail> OrderSlipDetails { get; set; }
    }
}
