//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPayment()
        {
            this.OrderInvoicePayments = new HashSet<OrderInvoicePayment>();
        }
    
        public int Id { get; set; }
        public string OrderReference { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> amount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<double> ConversionRate { get; set; }
        public string TransactionId { get; set; }
        public string CardNumber { get; set; }
        public string CardBrand { get; set; }
        public string CardExpiration { get; set; }
        public string CardHolder { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInvoicePayment> OrderInvoicePayments { get; set; }
    }
}
