//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageViewed
    {
        public int PageId { get; set; }
        public int ShopId { get; set; }
        public int DateRangeId { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public Nullable<int> counter { get; set; }
    
        public virtual DateRanx DateRanx { get; set; }
        public virtual Page Page { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
