//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDownload
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string DisplayFilename { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public Nullable<int> NbDaysAccessible { get; set; }
        public Nullable<int> NbDownloadable { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> IsShareable { get; set; }
    }
}
