//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttributeShop
    {
        public int ProductAttributeId { get; set; }
        public int ShopId { get; set; }
        public Nullable<double> WholesalePrice { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> ecotax { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> UnitPriceImpact { get; set; }
        public Nullable<int> DefaultOn { get; set; }
        public Nullable<int> MinimalQuantity { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
    
        public virtual ProductAttribute ProductAttribute { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
