//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductAttribute()
        {
            this.ProductAttributeShops = new HashSet<ProductAttributeShop>();
            this.WarehouseProductLocations = new HashSet<WarehouseProductLocation>();
            this.Attributes = new HashSet<Attribute>();
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string reference { get; set; }
        public string SupplierReference { get; set; }
        public string location { get; set; }
        public string ean13 { get; set; }
        public string upc { get; set; }
        public Nullable<double> WholesalePrice { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> ecotax { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> UnitPriceImpact { get; set; }
        public Nullable<int> DefaultOn { get; set; }
        public Nullable<int> MinimalQuantity { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttributeShop> ProductAttributeShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseProductLocation> WarehouseProductLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attribute> Attributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
