//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CategoryProducts = new HashSet<CategoryProduct>();
            this.CompareProducts = new HashSet<CompareProduct>();
            this.FeatureProducts = new HashSet<FeatureProduct>();
            this.LayeredPriceIndexes = new HashSet<LayeredPriceIndex>();
            this.ProductCarriers = new HashSet<ProductCarrier>();
            this.ProductCountryTaxes = new HashSet<ProductCountryTax>();
            this.ProductGroupReductionCaches = new HashSet<ProductGroupReductionCach>();
            this.ProductLangs = new HashSet<ProductLang>();
            this.ProductShops = new HashSet<ProductShop>();
            this.ProductTags = new HashSet<ProductTag>();
            this.SceneProducts = new HashSet<SceneProduct>();
            this.SearchIndexes = new HashSet<SearchIndex>();
            this.SpecificPricePriorities = new HashSet<SpecificPricePriority>();
            this.WarehouseProductLocations = new HashSet<WarehouseProductLocation>();
            this.Attachments = new HashSet<Attachment>();
            this.ProductCommentCriterions = new HashSet<ProductCommentCriterion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> CategoryDefaultId { get; set; }
        public Nullable<int> ShopDefaultId { get; set; }
        public Nullable<int> TaxRulesGroupId { get; set; }
        public Nullable<int> OnSale { get; set; }
        public Nullable<int> OnlineOnly { get; set; }
        public string ean13 { get; set; }
        public string upc { get; set; }
        public Nullable<double> ecotax { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> MinimalQuantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> WholesalePrice { get; set; }
        public string unity { get; set; }
        public Nullable<double> UnitPriceRatio { get; set; }
        public Nullable<double> AdditionalShippingCost { get; set; }
        public string reference { get; set; }
        public string SupplierReference { get; set; }
        public string location { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> OutOfStock { get; set; }
        public Nullable<int> QuantityDiscount { get; set; }
        public Nullable<int> customizable { get; set; }
        public Nullable<int> UploadableFiles { get; set; }
        public Nullable<int> TextFields { get; set; }
        public Nullable<int> active { get; set; }
        public string RedirectType { get; set; }
        public Nullable<int> ProductRedirectedId { get; set; }
        public Nullable<int> AvailableForOrder { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string condition { get; set; }
        public Nullable<int> ShowPrice { get; set; }
        public Nullable<int> indexed { get; set; }
        public string visibility { get; set; }
        public Nullable<int> CacheIsPack { get; set; }
        public Nullable<int> CacheHasAttachments { get; set; }
        public Nullable<int> IsVirtual { get; set; }
        public Nullable<int> CacheDefaultAttribute { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
        public Nullable<int> AdvancedStockManagement { get; set; }
        public Nullable<int> PackStockType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryProduct> CategoryProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompareProduct> CompareProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureProduct> FeatureProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayeredPriceIndex> LayeredPriceIndexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCarrier> ProductCarriers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCountryTax> ProductCountryTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGroupReductionCach> ProductGroupReductionCaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLang> ProductLangs { get; set; }
        public virtual ProductSale ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductShop> ProductShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTag> ProductTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceneProduct> SceneProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchIndex> SearchIndexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificPricePriority> SpecificPricePriorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseProductLocation> WarehouseProductLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCommentCriterion> ProductCommentCriterions { get; set; }
    }
}
