//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupplier
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductAttributeId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string ProductSupplierReference { get; set; }
        public Nullable<double> ProductSupplierPriceTe { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    }
}
