//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShop
    {
        public int ProductId { get; set; }
        public int ShopId { get; set; }
        public Nullable<int> CategoryDefaultId { get; set; }
        public Nullable<int> TaxRulesGroupId { get; set; }
        public Nullable<int> OnSale { get; set; }
        public Nullable<int> OnlineOnly { get; set; }
        public Nullable<double> ecotax { get; set; }
        public Nullable<int> MinimalQuantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> WholesalePrice { get; set; }
        public string unity { get; set; }
        public Nullable<double> UnitPriceRatio { get; set; }
        public Nullable<double> AdditionalShippingCost { get; set; }
        public Nullable<int> customizable { get; set; }
        public Nullable<int> UploadableFiles { get; set; }
        public Nullable<int> TextFields { get; set; }
        public Nullable<int> active { get; set; }
        public string RedirectType { get; set; }
        public Nullable<int> ProductRedirectedId { get; set; }
        public Nullable<int> AvailableForOrder { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string condition { get; set; }
        public Nullable<int> ShowPrice { get; set; }
        public Nullable<int> indexed { get; set; }
        public string visibility { get; set; }
        public Nullable<int> CacheDefaultAttribute { get; set; }
        public Nullable<int> AdvancedStockManagement { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
        public Nullable<int> PackStockType { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
