//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCommentGrade
    {
        public int ProductCommentId { get; set; }
        public int ProductCommentCriterionId { get; set; }
        public Nullable<int> grade { get; set; }
    
        public virtual ProductCommentCriterion ProductCommentCriterion { get; set; }
        public virtual ProductComment ProductComment { get; set; }
    }
}
