//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLang
    {
        public int ProductId { get; set; }
        public int ShopId { get; set; }
        public int LanguageId { get; set; }
        public string description { get; set; }
        public string DescriptionShort { get; set; }
        public string LinkRewrite { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaTitle { get; set; }
        public string name { get; set; }
        public string AvailableNow { get; set; }
        public string AvailableLater { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
