//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangeWeight
    {
        public int Id { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<double> delimiter1 { get; set; }
        public Nullable<double> delimiter2 { get; set; }
    }
}
