//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiamMarketEntities4 : DbContext
    {
        public SiamMarketEntities4()
            : base("name=SiamMarketEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressFormat> AddressFormats { get; set; }
        public virtual DbSet<AdviceLang> AdviceLangs { get; set; }
        public virtual DbSet<Advice> Advices { get; set; }
        public virtual DbSet<Alias> Aliases { get; set; }
        public virtual DbSet<AttachmentLang> AttachmentLangs { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<AttributeGroupLang> AttributeGroupLangs { get; set; }
        public virtual DbSet<AttributeGroup> AttributeGroups { get; set; }
        public virtual DbSet<AttributeImpact> AttributeImpacts { get; set; }
        public virtual DbSet<AttributeLang> AttributeLangs { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<BadgeLang> BadgeLangs { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<CarrierLanguage> CarrierLanguages { get; set; }
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<CarrierTaxRulesGroupShop> CarrierTaxRulesGroupShops { get; set; }
        public virtual DbSet<CartRuleCombination> CartRuleCombinations { get; set; }
        public virtual DbSet<CartRuleLang> CartRuleLangs { get; set; }
        public virtual DbSet<CartRuleProductRuleGroup> CartRuleProductRuleGroups { get; set; }
        public virtual DbSet<CartRuleProductRule> CartRuleProductRules { get; set; }
        public virtual DbSet<CartRuleProductRuleValue> CartRuleProductRuleValues { get; set; }
        public virtual DbSet<CartRule> CartRules { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryLanguage> CategoryLanguages { get; set; }
        public virtual DbSet<CategoryProduct> CategoryProducts { get; set; }
        public virtual DbSet<CategoryShop> CategoryShops { get; set; }
        public virtual DbSet<Cm> Cms { get; set; }
        public virtual DbSet<CmsBlockLang> CmsBlockLangs { get; set; }
        public virtual DbSet<CmsBlockPage> CmsBlockPages { get; set; }
        public virtual DbSet<CmsBlock> CmsBlocks { get; set; }
        public virtual DbSet<CmsCategory> CmsCategories { get; set; }
        public virtual DbSet<CmsCategoryLanguage> CmsCategoryLanguages { get; set; }
        public virtual DbSet<CmsLang> CmsLangs { get; set; }
        public virtual DbSet<CompareProduct> CompareProducts { get; set; }
        public virtual DbSet<Compare> Compares { get; set; }
        public virtual DbSet<ConditionAdvice> ConditionAdvices { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<ConfigurationKpiLanguage> ConfigurationKpiLanguages { get; set; }
        public virtual DbSet<ConfigurationKpi> ConfigurationKpis { get; set; }
        public virtual DbSet<ConfigurationLanguage> ConfigurationLanguages { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<ConnectionsPage> ConnectionsPages { get; set; }
        public virtual DbSet<ConnectionsSource> ConnectionsSources { get; set; }
        public virtual DbSet<ContactLanguage> ContactLanguages { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountryLanguage> CountryLanguages { get; set; }
        public virtual DbSet<Cronjob> Cronjobs { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyShop> CurrencyShops { get; set; }
        public virtual DbSet<CustomerMessage> CustomerMessages { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerThread> CustomerThreads { get; set; }
        public virtual DbSet<CustomizationFieldLang> CustomizationFieldLangs { get; set; }
        public virtual DbSet<CustomizationField> CustomizationFields { get; set; }
        public virtual DbSet<Customization> Customizations { get; set; }
        public virtual DbSet<CustomizedData> CustomizedDatas { get; set; }
        public virtual DbSet<DateRanx> DateRanges { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FeatureLang> FeatureLangs { get; set; }
        public virtual DbSet<FeatureProduct> FeatureProducts { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<FeatureValueLang> FeatureValueLangs { get; set; }
        public virtual DbSet<FeatureValue> FeatureValues { get; set; }
        public virtual DbSet<GenderLang> GenderLangs { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GroupLanguage> GroupLanguages { get; set; }
        public virtual DbSet<GroupReduction> GroupReductions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<HomesliderSlide> HomesliderSlides { get; set; }
        public virtual DbSet<HomesliderSlidesLang> HomesliderSlidesLangs { get; set; }
        public virtual DbSet<HookAlia> HookAlias { get; set; }
        public virtual DbSet<HookModuleException> HookModuleExceptions { get; set; }
        public virtual DbSet<HookModule> HookModules { get; set; }
        public virtual DbSet<Hook> Hooks { get; set; }
        public virtual DbSet<ImageLang> ImageLangs { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageType> ImageTypes { get; set; }
        public virtual DbSet<ImportMatch> ImportMatches { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<InfoLang> InfoLangs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LayeredCategory> LayeredCategories { get; set; }
        public virtual DbSet<LayeredFilter> LayeredFilters { get; set; }
        public virtual DbSet<LayeredFriendlyUrl> LayeredFriendlyUrls { get; set; }
        public virtual DbSet<LayeredIndexableAttributeGroupLangValue> LayeredIndexableAttributeGroupLangValues { get; set; }
        public virtual DbSet<LayeredIndexableAttributeGroup> LayeredIndexableAttributeGroups { get; set; }
        public virtual DbSet<LayeredIndexableAttributeLangValue> LayeredIndexableAttributeLangValues { get; set; }
        public virtual DbSet<LayeredIndexableFeatureLangValue> LayeredIndexableFeatureLangValues { get; set; }
        public virtual DbSet<LayeredIndexableFeature> LayeredIndexableFeatures { get; set; }
        public virtual DbSet<LayeredIndexableFeatureValueLangValue> LayeredIndexableFeatureValueLangValues { get; set; }
        public virtual DbSet<LayeredPriceIndex> LayeredPriceIndexes { get; set; }
        public virtual DbSet<Linksmenutop> Linksmenutops { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Mail> Mails { get; set; }
        public virtual DbSet<ManufacturerLang> ManufacturerLangs { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<MemcachedServer> MemcachedServers { get; set; }
        public virtual DbSet<MessageReaded> MessageReadeds { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MetaLang> MetaLangs { get; set; }
        public virtual DbSet<Meta> Metas { get; set; }
        public virtual DbSet<ModuleAccess> ModuleAccesses { get; set; }
        public virtual DbSet<ModuleCountry> ModuleCountries { get; set; }
        public virtual DbSet<ModuleCurrency> ModuleCurrencies { get; set; }
        public virtual DbSet<ModuleGroup> ModuleGroups { get; set; }
        public virtual DbSet<ModulePreference> ModulePreferences { get; set; }
        public virtual DbSet<ModuleShop> ModuleShops { get; set; }
        public virtual DbSet<Newsletter> Newsletters { get; set; }
        public virtual DbSet<OperatingSystem> OperatingSystems { get; set; }
        public virtual DbSet<OrderCarrier> OrderCarriers { get; set; }
        public virtual DbSet<OrderCartRule> OrderCartRules { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderHistory> OrderHistories { get; set; }
        public virtual DbSet<OrderInvoicePayment> OrderInvoicePayments { get; set; }
        public virtual DbSet<OrderInvoice> OrderInvoices { get; set; }
        public virtual DbSet<OrderMessageLang> OrderMessageLangs { get; set; }
        public virtual DbSet<OrderMessage> OrderMessages { get; set; }
        public virtual DbSet<OrderPayment> OrderPayments { get; set; }
        public virtual DbSet<OrderReturnDetail> OrderReturnDetails { get; set; }
        public virtual DbSet<OrderReturn> OrderReturns { get; set; }
        public virtual DbSet<OrderReturnStateLang> OrderReturnStateLangs { get; set; }
        public virtual DbSet<OrderReturnState> OrderReturnStates { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderSlipDetail> OrderSlipDetails { get; set; }
        public virtual DbSet<OrderSlip> OrderSlips { get; set; }
        public virtual DbSet<OrderStateLang> OrderStateLangs { get; set; }
        public virtual DbSet<OrderState> OrderStates { get; set; }
        public virtual DbSet<Pack> Packs { get; set; }
        public virtual DbSet<Pagenotfound> Pagenotfounds { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PageType> PageTypes { get; set; }
        public virtual DbSet<PageViewed> PageVieweds { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductAttributeShop> ProductAttributeShops { get; set; }
        public virtual DbSet<ProductCarrier> ProductCarriers { get; set; }
        public virtual DbSet<ProductCommentCriterionLang> ProductCommentCriterionLangs { get; set; }
        public virtual DbSet<ProductCommentCriterion> ProductCommentCriterions { get; set; }
        public virtual DbSet<ProductCommentGrade> ProductCommentGrades { get; set; }
        public virtual DbSet<ProductComment> ProductComments { get; set; }
        public virtual DbSet<ProductCommentUsefulness> ProductCommentUsefulnesses { get; set; }
        public virtual DbSet<ProductCountryTax> ProductCountryTaxes { get; set; }
        public virtual DbSet<ProductDownload> ProductDownloads { get; set; }
        public virtual DbSet<ProductGroupReductionCach> ProductGroupReductionCaches { get; set; }
        public virtual DbSet<ProductLang> ProductLangs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<ProductShop> ProductShops { get; set; }
        public virtual DbSet<ProductSupplier> ProductSuppliers { get; set; }
        public virtual DbSet<ProductTag> ProductTags { get; set; }
        public virtual DbSet<ProfileLanguage> ProfileLanguages { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<QuickAccess> QuickAccesses { get; set; }
        public virtual DbSet<QuickAccessLang> QuickAccessLangs { get; set; }
        public virtual DbSet<RangePrice> RangePrices { get; set; }
        public virtual DbSet<RangeWeight> RangeWeights { get; set; }
        public virtual DbSet<Referrer> Referrers { get; set; }
        public virtual DbSet<ReferrerShop> ReferrerShops { get; set; }
        public virtual DbSet<RequestSql> RequestSqls { get; set; }
        public virtual DbSet<RequiredField> RequiredFields { get; set; }
        public virtual DbSet<RiskLang> RiskLangs { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<SceneLang> SceneLangs { get; set; }
        public virtual DbSet<SceneProduct> SceneProducts { get; set; }
        public virtual DbSet<Scene> Scenes { get; set; }
        public virtual DbSet<SearchEngine> SearchEngines { get; set; }
        public virtual DbSet<SearchIndex> SearchIndexes { get; set; }
        public virtual DbSet<SearchWord> SearchWords { get; set; }
        public virtual DbSet<Sekeyword> Sekeywords { get; set; }
        public virtual DbSet<Shelf> Shelves { get; set; }
        public virtual DbSet<ShopGroup> ShopGroups { get; set; }
        public virtual DbSet<ShopLanguage> ShopLanguages { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopUrl> ShopUrls { get; set; }
        public virtual DbSet<SmartyCach> SmartyCaches { get; set; }
        public virtual DbSet<SpecificPricePriority> SpecificPricePriorities { get; set; }
        public virtual DbSet<SpecificPriceRuleConditionGroup> SpecificPriceRuleConditionGroups { get; set; }
        public virtual DbSet<SpecificPriceRuleCondition> SpecificPriceRuleConditions { get; set; }
        public virtual DbSet<SpecificPriceRule> SpecificPriceRules { get; set; }
        public virtual DbSet<SpecificPrice> SpecificPrices { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Statssearch> Statssearches { get; set; }
        public virtual DbSet<StockAvailable> StockAvailables { get; set; }
        public virtual DbSet<StockMvtReasonLang> StockMvtReasonLangs { get; set; }
        public virtual DbSet<StockMvtReason> StockMvtReasons { get; set; }
        public virtual DbSet<StockMvt> StockMvts { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<SupplierLang> SupplierLangs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplyOrderDetail> SupplyOrderDetails { get; set; }
        public virtual DbSet<SupplyOrderHistory> SupplyOrderHistories { get; set; }
        public virtual DbSet<SupplyOrderReceiptHistory> SupplyOrderReceiptHistories { get; set; }
        public virtual DbSet<SupplyOrder> SupplyOrders { get; set; }
        public virtual DbSet<SupplyOrderStateLang> SupplyOrderStateLangs { get; set; }
        public virtual DbSet<SupplyOrderState> SupplyOrderStates { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<SystemModule> SystemModules { get; set; }
        public virtual DbSet<TabLanguage> TabLanguages { get; set; }
        public virtual DbSet<TabModulePreference> TabModulePreferences { get; set; }
        public virtual DbSet<Tab> Tabs { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TaxLang> TaxLangs { get; set; }
        public virtual DbSet<TaxRule> TaxRules { get; set; }
        public virtual DbSet<TaxRulesGroup> TaxRulesGroups { get; set; }
        public virtual DbSet<Themeconfigurator> Themeconfigurators { get; set; }
        public virtual DbSet<ThemeMeta> ThemeMetas { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<ThemeSpecific> ThemeSpecifics { get; set; }
        public virtual DbSet<Timezone> Timezones { get; set; }
        public virtual DbSet<UserBook> UserBooks { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<WarehouseProductLocation> WarehouseProductLocations { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WebBrowser> WebBrowsers { get; set; }
        public virtual DbSet<WebserviceAccount> WebserviceAccounts { get; set; }
        public virtual DbSet<WebservicePermission> WebservicePermissions { get; set; }
        public virtual DbSet<WishlistProduct> WishlistProducts { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
