//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Referrer()
        {
            this.ReferrerShops = new HashSet<ReferrerShop>();
            this.ConnectionsSources = new HashSet<ConnectionsSource>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string passwd { get; set; }
        public string HttpRefererRegexp { get; set; }
        public string HttpRefererLike { get; set; }
        public string RequestUriRegexp { get; set; }
        public string RequestUriLike { get; set; }
        public string HttpRefererRegexpNot { get; set; }
        public string HttpRefererLikeNot { get; set; }
        public string RequestUriRegexpNot { get; set; }
        public string RequestUriLikeNot { get; set; }
        public Nullable<double> BaseFee { get; set; }
        public Nullable<double> PercentFee { get; set; }
        public Nullable<double> ClickFee { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferrerShop> ReferrerShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectionsSource> ConnectionsSources { get; set; }
    }
}
