//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferrerShop
    {
        public int ReferrerId { get; set; }
        public int ShopId { get; set; }
        public Nullable<int> CacheVisitors { get; set; }
        public Nullable<int> CacheVisits { get; set; }
        public Nullable<int> CachePages { get; set; }
        public Nullable<int> CacheRegistrations { get; set; }
        public Nullable<int> CacheOrders { get; set; }
        public Nullable<double> CacheSales { get; set; }
        public Nullable<double> CacheRegRate { get; set; }
        public Nullable<double> CacheOrderRate { get; set; }
    
        public virtual Referrer Referrer { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
