//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopUrl
    {
        public int Id { get; set; }
        public string Domain { get; set; }
        public string DomainSsl { get; set; }
        public string PhysicalUri { get; set; }
        public string VirtualUri { get; set; }
        public Nullable<int> Shop_Id { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
