//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificPrice
    {
        public int Id { get; set; }
        public Nullable<int> SpecificPriceRuleId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProductAttributeId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> FromQuantity { get; set; }
        public Nullable<double> reduction { get; set; }
        public Nullable<int> ReductionTax { get; set; }
        public string ReductionType { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
    }
}
