//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int Id { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string name { get; set; }
        public string IsoCode { get; set; }
        public Nullable<int> TaxBehavior { get; set; }
        public Nullable<int> active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CountryId_Id { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
