//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAvailable
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductAttributeId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> DependsOnStock { get; set; }
        public Nullable<int> OutOfStock { get; set; }
    }
}
