//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMvt
    {
        public int Id { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SupplyOrderId { get; set; }
        public Nullable<int> StockMvtReasonId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeLastname { get; set; }
        public string EmployeeFirstname { get; set; }
        public Nullable<int> PhysicalQuantity { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<int> sign { get; set; }
        public Nullable<double> PriceTe { get; set; }
        public Nullable<double> LastWa { get; set; }
        public Nullable<double> CurrentWa { get; set; }
        public Nullable<long> referer { get; set; }
    }
}
