//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrderHistory
    {
        public int Id { get; set; }
        public Nullable<int> SupplyOrderId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeLastname { get; set; }
        public string EmployeeFirstname { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    }
}
