//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrderState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplyOrderState()
        {
            this.SupplyOrderStateLangs = new HashSet<SupplyOrderStateLang>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeliveryNote { get; set; }
        public Nullable<int> editable { get; set; }
        public Nullable<int> ReceiptState { get; set; }
        public Nullable<int> PendingReceipt { get; set; }
        public Nullable<int> enclosed { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyOrderStateLang> SupplyOrderStateLangs { get; set; }
    }
}
