//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrder
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> SupplyOrderStateId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> RefCurrencyId { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
        public Nullable<System.DateTime> DateDeliveryExpected { get; set; }
        public Nullable<double> TotalTe { get; set; }
        public Nullable<double> TotalWithDiscountTe { get; set; }
        public Nullable<double> TotalTax { get; set; }
        public Nullable<double> TotalTi { get; set; }
        public Nullable<double> DiscountRate { get; set; }
        public Nullable<double> DiscountValueTe { get; set; }
        public Nullable<int> IsTemplate { get; set; }
    }
}
