//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> SupplyOrderId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductAttributeId { get; set; }
        public string reference { get; set; }
        public string SupplierReference { get; set; }
        public string name { get; set; }
        public string ean13 { get; set; }
        public string upc { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<double> UnitPriceTe { get; set; }
        public Nullable<int> QuantityExpected { get; set; }
        public Nullable<int> QuantityReceived { get; set; }
        public Nullable<double> PriceTe { get; set; }
        public Nullable<double> DiscountRate { get; set; }
        public Nullable<double> DiscountValueTe { get; set; }
        public Nullable<double> PriceWithDiscountTe { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public Nullable<double> PriceTi { get; set; }
        public Nullable<double> TaxValueWithOrderDiscount { get; set; }
        public Nullable<double> PriceWithOrderDiscountTe { get; set; }
    }
}
