//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabModulePreference
    {
        public int Id { get; set; }
        public string Module { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Tab_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Tab Tab { get; set; }
    }
}
