//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRule
    {
        public int Id { get; set; }
        public Nullable<int> TaxRulesGroupId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZipcodeFrom { get; set; }
        public string ZipcodeTo { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<int> behavior { get; set; }
        public string description { get; set; }
    }
}
