//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themeconfigurator
    {
        public int ItemId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public string title { get; set; }
        public Nullable<int> TitleUse { get; set; }
        public string hook { get; set; }
        public string url { get; set; }
        public Nullable<int> target { get; set; }
        public string image { get; set; }
        public string ImageW { get; set; }
        public string ImageH { get; set; }
        public string html { get; set; }
        public Nullable<int> active { get; set; }
    }
}
