//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeSpecific
    {
        public int ThemeId { get; set; }
        public int ShopId { get; set; }
        public int entity { get; set; }
        public int ObjectId { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
