//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBook
    {
        public int BookId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Shelf_Id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Shelf Shelf { get; set; }
    }
}
