//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseProductLocation
    {
        public int Id { get; set; }
        public string location { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> ProductAttribute_Id { get; set; }
        public Nullable<int> Warehouse_Id { get; set; }
    
        public virtual ProductAttribute ProductAttribute { get; set; }
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
