//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebservicePermission
    {
        public int Id { get; set; }
        public string Resource { get; set; }
        public string Method { get; set; }
        public Nullable<int> WebserviceAccount_Id { get; set; }
    
        public virtual WebserviceAccount WebserviceAccount { get; set; }
    }
}
